[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
  "provider/backlog.py",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
